### ISSUE TITLE
Required tools and software

### ISSUE THREAD

**Issue by totaldis** [yearography/hackathon#1]
We probably need access to use apt-get and npm to install packages.

**Comment by jamie1911** [comment]
just sudo or let me know what you need

**Comment by totaldis** [comment]
tried that... maybe you have some ports blocked

```
After this operation, 21.6 MB of additional disk space will be used.
Do you want to continue? [Y/n] Y
0% [Connecting to us.archive.ubuntu.com (2001:67c:1562::13)]
```

**Comment by jamie1911** [comment]
IPv6?? Wtf maybe need to disable it in sysctl.conf

**Comment by totaldis** [comment]
http://www.pcmag.com/article2/0,2817,2484216,00.asp

**Comment by jamie1911** [comment]
Palm beach county owns a whole class B subnet.. We arnt running that much out

**Comment by jamie1911** [comment]
all set.
